/* Composiciones animadas. Las notas y el temario permanecen en slides.js. */
(() => {
 const s=window.SLIDES;
 s.forEach((slide,i)=>{slide.type=(slide.type||'')+' scene-'+(i+1);});
 s[0].body=`<img class="art" src="assets/broadcast.webp" alt="Antena plateada que proyecta ondas de luz sobre un fondo negro"><p class="eyebrow">FÓRMULA JUMPERS / MÓDULO ADS</p><h1><span class="title-line">TRÁFICO</span><span class="title-line outline">PAGO.</span></h1><div class="cover-bottom"><p class="lede">Desde cero hasta tu primera campaña.<br>WhatsApp & Instagram.</p><button class="start-button" data-next>COMENZAR <span>↗</span></button></div><span class="edition">JOSÉ BAYONA<br>FORMACIÓN EN NEGOCIOS</span>`;
 s[2].body=`<p class="eyebrow">ELECCIÓN DE RUTA</p><h2>¿DÓNDE EMPIEZA<br>LA CONVERSACIÓN?</h2><div class="route-choices"><button class="route-choice" data-route="wa" aria-pressed="true"><span>01 / CONTACTO DIRECTO</span><strong>WhatsApp ↗</strong></button><button class="route-choice" data-route="ig" aria-pressed="false"><span>02 / CONTENIDO Y CONTEXTO</span><strong>Instagram ↗</strong></button></div><div class="route-detail" aria-live="polite"><h3 id="route-heading">Del anuncio al chat.</h3><p id="route-text">Para cuando puedes responder, entender la necesidad y proponer un siguiente paso.</p><p id="route-signal" class="tagline">SEÑAL: CONVERSACIONES CALIFICADAS</p></div><p class="inline-note">Elige una ruta para ver el recorrido. Una visita al perfil todavía no es un lead.</p>`;
 s[9].body=`<p class="eyebrow">05 / CREACIÓN DEL ANUNCIO</p><h2>UN MENSAJE.<br>UNA ACCIÓN.</h2><div class="creative-sequence"><div data-sequence="0"><span class="step">01 / APERTURA</span><h3>Gancho</h3><p>Una situación relevante que invite a prestar atención.</p><div class="sequence-line"></div></div><div data-sequence="1"><span class="step">02 / DESARROLLO</span><h3>Propuesta</h3><p>Qué ofreces, para quién y cómo funciona.</p><div class="sequence-line"></div></div><div data-sequence="2"><span class="step">03 / CIERRE</span><h3>Acción</h3><p>Una instrucción concreta hacia WhatsApp o tu perfil.</p><div class="sequence-line"></div></div></div><p class="callout">Video o imagen: el formato que te permita explicar mejor la propuesta.</p>`;
 s[11].body=`<p class="eyebrow">06 / ESTRUCTURA DE META ADS</p><h2>TRES NIVELES.<br>UNA CAMPAÑA.</h2><div class="hierarchy"><div><span class="level">01</span><h3>Campaña</h3><p>Qué resultado buscas.</p></div><div><span class="level">02</span><h3>Conjunto</h3><p>Público, ubicaciones y entrega.</p></div><div><span class="level">03</span><h3>Anuncio</h3><p>El mensaje y la pieza que verá la persona.</p></div></div><p class="inline-note">El presupuesto puede configurarse en campaña o conjunto, según la configuración elegida.</p>`;
 s[15].type+=' chat-scene';
 s[15].body=`<p class="eyebrow">09 / CASO DE PRÁCTICA · WHATSAPP</p><h2>DEL ANUNCIO<br>A LA CONVERSACIÓN.</h2><div class="chat-composition"><div class="ad-copy"><p class="tagline">EL ANUNCIO</p><blockquote>Una sesión para ordenar la oferta de tu servicio.</blockquote><p>“Escríbeme OFERTA para conocer cómo funciona”.</p><span class="small">Ejemplo didáctico / consultoría</span></div><div class="chat-demo" aria-label="Ejemplo animado de conversación"><div class="chat-header"><strong>Tu negocio</strong><span>Conversación de ejemplo</span></div><div class="message outgoing" data-chat="0">Hola, quiero información.<br>OFERTA</div><div class="message incoming" data-chat="1">Gracias por escribir. ¿Qué servicio ofreces y qué parte de tu oferta quieres aclarar?</div><div class="chat-result" data-chat="2">Comprender la necesidad y acordar el siguiente paso.</div></div></div>`;
 s[17].type+=' journey-scene';
 s[17].body=`<p class="eyebrow">10 / CASO DE PRÁCTICA · INSTAGRAM</p><h2>EL PERFIL COMPLETA<br>EL MENSAJE.</h2><p class="scenario">EJEMPLO DIDÁCTICO / SERVICIOS</p><div class="journey"><div><span class="journey-number">01</span><h3>Anuncio</h3><p>“En mi perfil te explico qué debe contener una oferta de servicios clara”.</p></div><div><span class="journey-number">02</span><h3>Perfil</h3><p>Una publicación fijada desarrolla la idea y explica el servicio.</p></div><div><span class="journey-number">03</span><h3>Contacto</h3><p>“Envíame OFERTA para conocer el acompañamiento”.</p></div></div><p class="callout">La pieza y el perfil deben sostener la misma expectativa.</p>`;
 s[20].type+=' calculator-scene';
 s[20].body=`<p class="eyebrow">12 / COSTOS COMERCIALES</p><h2>¿CUÁNTO CUESTA<br>UNA OPORTUNIDAD?</h2><div class="calculator"><div class="investment"><label for="investment">INVERSIÓN DE EJEMPLO · COP</label><output id="investment-value" for="investment">$100.000</output><input id="investment" type="range" min="20000" max="300000" step="10000" value="100000" aria-describedby="simulation-note"><p id="simulation-note">Mueve la inversión. Los resultados se mantienen fijos para practicar el cálculo, no son una proyección.</p></div><div class="cost-bars">${[[20,'conversaciones'],[10,'leads calificados'],[5,'citas'],[1,'venta']].map(([n,label],i)=>`<div class="cost-row"><div class="cost-label"><span>${n} ${label}</span><strong data-cost="${n}">$${(100000/n).toLocaleString('es-CO')}</strong></div><div class="cost-track"><div class="cost-fill" style="--target:${[100,50,25,5][i]}%"></div></div></div>`).join('')}</div></div><p class="callout">Costo por resultado = gasto ÷ resultados. Para evaluar rentabilidad, incluye margen y otros costos.</p>`;
 s[24].body=s[24].body.replace('<div class="checklist">','<div class="checklist" role="group" aria-label="Checklist de implementación">').replace(/<div><span>(\d\d)<\/span>([^<]+)<\/div>/g,'<button class="check-item" aria-pressed="false"><span>$1</span><span class="check-text">$2</span><b aria-hidden="true">+</b></button>')+`<p class="check-progress" aria-live="polite">0 de 8 comprobados</p>`;
 s[25].body=`<p class="eyebrow">FÓRMULA JUMPERS / TU PRIMERA DECISIÓN</p><h2><span>PUBLICA.</span><span class="outline">ATIENDE.</span><span>APRENDE.</span></h2><div class="closing-bottom"><p class="lede">¿Qué ocurrió?<br>¿Cuál será el siguiente ajuste?</p><button class="start-button" data-notes>RECURSOS DE CLASE <span>↗</span></button></div>`;
})();
